# Top-level configuration
name = "atelier-komune"
pages_build_output_dir = "./dist"
compatibility_flags = [ "nodejs_compat", "streams_enable_constructors" ]
compatibility_date = "2022-07-12"

[[d1_databases]]
binding = "DB"
database_name = "atelier-komune"
database_id = "8dbcf26a-11cb-494f-bc5f-edf9e56a296a"
migrations_dir = "./server/database/migrations"

[vars]
NUXT_BASE_URL = "https://atelierkomune.com"
